In [116]:
%pip install requests python-dotenv

Requirement already satisfied: requests in c:\anaconda\lib\site-packages (2.32.5)
Requirement already satisfied: python-dotenv in c:\anaconda\lib\site-packages (1.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\anaconda\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\anaconda\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\anaconda\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda\lib\site-packages (from requests) (2025.11.12)
Note: you may need to restart the kernel to use updated packages.

In [117]:
import os
import requests

from dotenv import load_dotenv

In [118]:
# TICKETMASTER 

load_dotenv("../.env")

TICKETMASTER_API_KEY = os.getenv("TICKETMASTER_API_KEY")

In [119]:
# ЧАСТЬ 1: Madison Square Garden
# попробую начать с одной площадки, найти её id и потом концерты, проходившие на ней

url = "https://app.ticketmaster.com/discovery/v2/venues.json"

params = {
    "apikey": TICKETMASTER_API_KEY,
    "keyword": "Madison Square Garden"
}

response = requests.get(
    url,
    params=params,
    timeout=30
)

In [120]:
response.status_code

200

In [121]:
data = response.json()

In [122]:
data.keys()

dict_keys(['_embedded', '_links', 'page'])

In [123]:
type(data["_embedded"])

dict

In [124]:
data["_embedded"].keys()

dict_keys(['venues'])

In [125]:
type(data["_embedded"]['venues'])

list

In [126]:
len(data["_embedded"]['venues'])

20

In [127]:
# изучим список площадок, которые мне выдала база
for i in range(20): 
    print(i, ':')
    print(f'name = {data["_embedded"]["venues"][i]["name"]}')   
    print(f'id = {data["_embedded"]["venues"][i]["id"]}') 
    print(f'upcomingEvents = {data["_embedded"]["venues"][i]["upcomingEvents"]}')

0 :
name = Madison Square Garden
id = KovZpZA7AAEA
upcomingEvents = {'tmr': 1, 'ticketmaster': 164, '_total': 165, '_filtered': 0}
1 :
name = madison square garden
id = Z1lMVSyiJynZad9jvPa7vo
upcomingEvents = {'_total': 0, '_filtered': 0}
2 :
name = Madison Square Garden
id = Za5ju3rKuqZBgOooTkG_eEQYHIAtk7FC5
upcomingEvents = {'_total': 0, '_filtered': 0}
3 :
name = Madison Square Garden
id = Za5ju3rKuqZBlKMw7ByqGnQZkRyWhuFPU
upcomingEvents = {'_total': 0, '_filtered': 0}
4 :
name = Madison Square Garden
id = Za5ju3rKuqZBoCa28eyq7KBpC6Ip2zUr5
upcomingEvents = {'_total': 0, '_filtered': 0}
5 :
name = Madison Square Garden
id = Za5ju3rKuqZDd8s8Ui3rs7H_ayTjIjy4Is
upcomingEvents = {'_total': 0, '_filtered': 0}
6 :
name = Madison Square Garden
id = Za5ju3rKuqZDdDrt2ShQAd1BxyJ9tJpHxJ
upcomingEvents = {'_total': 0, '_filtered': 0}
7 :
name = Madison Square Garden
id = Za5ju3rKuqZDdRyskGOmaFRIigA5R0zbgV
upcomingEvents = {'_total': 0, '_filtered': 0}
8 :
name = Madison Square Garden
id = Za5ju3rKuqZDdhH4UI3v4dpnre_O0vNoOD
upcomingEvents = {'_total': 0, '_filtered': 0}
9 :
name = Madison Square Garden
id = Za5ju3rKuqZDdwAzH8FAy1BaYA69TAD7Nd
upcomingEvents = {'_total': 0, '_filtered': 0}
10 :
name = Madison Square Garden
id = Za5ju3rKuqZDdxWxwUEsa5et9M7Ebrcvp9
upcomingEvents = {'_total': 0, '_filtered': 0}
11 :
name = Madison Square Garden
id = Za5ju3rKuqZDeDmIojZ3WACIc7yEo1jhNa
upcomingEvents = {'_total': 0, '_filtered': 0}
12 :
name = Madison Square Garden
id = Za5ju3rKuqZDeGViXT6WoF75X6DNNzZpZu
upcomingEvents = {'_total': 0, '_filtered': 0}
13 :
name = Madison Square Garden
id = Za5ju3rKuqZDeiHhr00wcdVhY4p9SZkMpf
upcomingEvents = {'_total': 0, '_filtered': 0}
14 :
name = Madison Square Garden
id = Za5ju3rKuqZDv8mMivxUACKtKhT7rDXfsr
upcomingEvents = {'_total': 0, '_filtered': 0}
15 :
name = Madison Square Garden
id = Za5ju3rKuqZDv9o0xpppavbaRjpYwTYxHz
upcomingEvents = {'_total': 0, '_filtered': 0}
16 :
name = Madison Square Garden
id = Za5ju3rKuqZDvKkhq3Y5ovjDLevyBRhtqL
upcomingEvents = {'_total': 0, '_filtered': 0}
17 :
name = Madison Square Garden
id = Za5ju3rKuqZDvZx85FjZP17B9FbXVsSl4V
upcomingEvents = {'_total': 0, '_filtered': 0}
18 :
name = Madison Square Garden
id = Za5ju3rKuqZDvhbsov0bu5el28uEbFlKQo
upcomingEvents = {'_total': 0, '_filtered': 0}
19 :
name = Madison Square Garden
id = Za5ju3rKuqZDvqEp6m3pqaNt1uxUJ4zIuz
upcomingEvents = {'_total': 0, '_filtered': 0}

In [128]:
# Ticketmaster возвращает несколько записей с названием Madison Square Garden и разными id
# именно первая в списке запись действительно представляет Madison Square Garden
# так как на ней запланированы мероприятия в отличие от остальных, буду работать с ней

data["_embedded"]["venues"][0]

{'name': 'Madison Square Garden',
 'type': 'venue',
 'id': 'KovZpZA7AAEA',
 'test': False,
 'url': 'https://www.ticketmaster.com/madison-square-garden-tickets-new-york/venue/483329',
 'locale': 'en-us',
 'aliases': ['msg', 'madison square garden'],
 'images': [{'ratio': '16_9',
   'url': 'https://s1.ticketm.net/dbimages/23135v.jpg',
   'width': 640,
   'height': 360,
   'fallback': False}],
 'postalCode': '10001',
 'timezone': 'America/New_York',
 'city': {'name': 'New York'},
 'state': {'name': 'New York', 'stateCode': 'NY'},
 'country': {'name': 'United States Of America', 'countryCode': 'US'},
 'address': {'line1': '7th Ave & 32nd Street'},
 'location': {'longitude': '-73.99160060', 'latitude': '40.74970620'},
 'markets': [{'name': 'New York/Tri-State Area', 'id': '35'},
  {'name': 'All of US', 'id': '51'},
  {'name': 'Northern New Jersey', 'id': '55'},
  {'name': 'Connecticut', 'id': '124'}],
 'dmas': [{'id': 200}, {'id': 296}, {'id': 345}, {'id': 422}],
 'social': {'twitter': {'handle': '@TheGarden'}},
 'boxOfficeInfo': {'phoneNumberDetail': 'General Info: (212) 465-MSG1 (6741) or (212) 247-4777 Knicks Information: 1(877) NYK-DUNK. Rangers Fan Line: (212) 465-4459. Liberty Hotline: (212) 564-WNBA (9622). Season Subscriptions: (212) 465-6073. Disabled Services: (212) 465-6034 Guest Relations: (212) 465 - 6225 Group Sales: (212) 465-6100 Lost and Found: (212) 465-6299',
  'openHoursDetail': "Monday - Saturday: 12:00pm to 6:00pm **Tickets are not on-sale at the Box Office on the first day an event goes on-sale** The Box Office will be open at 12:00pm daily or 90 minutes before the 1st performance of the day, whichever is earlier and will stay open until 8:00pm or 30 minutes after the last performance of the day begins, whichever is later. Sunday - Closed If an event takes place on Sunday, Box Office will open 90 minutes before the event start time and remain open 1 hour after event start time for Will Call and tickets sales for the evening's event only.",
  'acceptedPaymentDetail': 'American Express, Visa, MasterCard, Discover. ATM machines are located in Chase Square.',
  'willCallDetail': 'Pick-up tickets anytime the day of the show during box office hours (see above). Customers must present the actual credit card used to place the order and a picture ID. MSG cannot accept third party or “drop offs” from individual patrons.'},
 'parkingDetail': 'Prepaid advance parking is available for select events through Ticketmaster or via a link on www.thegarden.com. Madison Square Garden does not own or operate any parking facility.',
 'accessibleSeatingDetail': "MSG WHEELCHAIR AND TRANSFER SEATING POLICY: Wheelchair and Transfer seating is reserved exclusively for patrons with accessible needs and their companions. Accessible seating is intended for use by an individual with a mobility disability or other disability who requires the accessible features of accessible seating due to a disability, and that individual's companions. Madison Square Garden (MSG) reserves the right to investigate potential misuse of accessible seating and to take all appropriate action against individuals who fraudulently obtain tickets for accessible seating. While tickets for accessible seating legitimately purchased for the use of an individual with disability may be transferred to another individual under the same terms and conditions applicable to other tickets, in the event such ticket is transferred to a non-disabled individual, MSG reserves the right to transfer that individual to other available seating TO ORDER WHEELCHAIR AND TRANSFER SEATING: Tickets for people with accessible needs, subject to availability, may be purchased in several ways: 1) Call Ticketmaster at 866-858-0008 2) Call MSG's Disabled Services Department at (212)465-6115. 3) Visit Madison Square Garden's Box Office (see box office hours above) 4) Order Online with Ticketmaster (select your event from the list to the left) For additional information regarding accessibility at Madison Square Garden or to request any other accommodations, please call MSG's Disabled Services Department at (212) 465-6115 any weekday between 9:30am-4:30pm ET. Service Animals Pets are not permitted at Madison Square Garden. MSG has very specific policies related to service and emotional support animals. Please visit www.thegarden.com to obtain more information for admitting your animal. Assistive listening devices (ALDAs) are available upon request. Please visit the Guest Experience Office across from section 117 for assistance. There is no charge for this service, however some form of identification will be requested and returned to you, once the device is checked back in. Wheelchair Storage: For patrons who wish to transfer to a seat from their wheelchair, we will store your mobility device at the Guest Experience Office. You will receive a claim check for your device. Wheelchair Escorts to Seats: Patrons with mobility impairments who do not have access to a wheelchair may request a wheelchair to transport the individual to/from their seat, free of charge. Please be aware that our personnel cannot remain with you during the event, nor will they allow you to remain in or keep the wheelchair for the duration of the event. In the event a patron requires the use of a wheelchair for the duration of the event, we recommend bringing your own wheelchair or other mobility device. The escort pick-up area is located on the South (toward 31st) side of Chase Square at elevator alcove. Please allow for extra so that you may be accommodated prior to the event start. Simply ask a Guest Experience Representative or a MSG Security Guard for assistance. Elevators: Public elevators are available for use by guests with disabilities and service every seating level",
 'generalInfo': {'generalRule': 'ARRIVE EARLY: Please arrive at least one-hour prior to event time. All patrons will go through a screening process upon entry with all packages, including briefcases and pocketbooks, being inspected prior to entry. Additionally, metal detectors may be utilized for some events. Bags that have passed inspection must fit comfortably under your seat.Please be mindful of traffic conditions, as Midtown Manhattan can be quite congested, especially during the holidays, parades, or special events. No smoking or electronic cigarettes permitted anywhere in the building No reentry. No recording devices No outside food or drink There are no bag or coat check facilities Alcohol Management: For most events at MSG, alcoholic beverages are available for purchase. MSG staff is trained in the nationally recognized T.E.A.M. (Techniques for Effective Alcohol Management) training program for responsible alcohol management. All guests will be required to show ID to purchase alcohol. Guests are not permitted to bring in alcoholic beverages from outside and may not leave with alcohol purchased inside the venue. Management reserves the right to refuse the sale of alcohol to any guest. Please be aware that it is the policy of The Madison Square Garden Company to require all guests who appear to be forty (40) years of age or younger to present a valid form of ID with proof of age in order to purchase alcoholic beverages at Madison Square Garden, Radio City Music Hall, The Beacon Theatre or The Chicago Theatre. Pursuant to applicable State law, MSG accepts only the following forms of identification: • A valid driver’s license or non-driver identification card issued by the United States Government, a State Government, Commonwealth, Possession or Territory of the United States or a Provincial Government of Canada. • A valid passport • A valid U.S. military ID International guests wishing to consume alcohol inside the building must bring a valid passport as the only form of acceptable ID.',
  'childRule': "For most events, all children who have reached their second birthday require a ticket to gain admittance to Madison Square Garden. Any child who has yet to reach their second birthday does not require a ticket, however, they may not occupy their own seat. Please note, that for certain children's events (such as the Wiggles and Sesame Street Live!), all children who have reached their first birthday require a ticket. Please check the event profile for your specific event for more information prior to your purchase of tickets."},
 'upcomingEvents': {'tmr': 1,
  'ticketmaster': 164,
  '_total': 165,
  '_filtered': 0},
 'ada': {'adaPhones': 'Inquiries or requests concerning accessibility should be directed to the Accessible Services Department for Madison Square Garden at 888-609-7599.',
  'adaCustomCopy': "Individuals with disabilities may purchase up to three seats for companions in the wheelchair or other accessible seating areas, provided such seats are available.  Additional tickets, if available, may be purchased as close to the accessible seating areas, as long as it does not exceed the ticket limit for the event.  Please note, for events or specific seating sections where ticket sales are limited to fewer than four tickets per patron, the same ticket restrictions will apply to the purchase of accessible seating.\n\nAccessible seating is intended for use by an individual with a mobility disability or other disability who requires the accessible features of accessible seating due to a disability, and that individual's companions.  Madison Square Garden reserves the right to investigate potential misuse of accessible seating and to take all appropriate action against individuals who fraudulently obtain tickets for accessible seating.  While tickets for accessible seating legitimately purchased for the use of an individual with disability may be transferred to another individual under the same terms and conditions applicable to other tickets, in the event such ticket is transferred to a nondisabled individual, Madison Square Garden reserves the right to transfer that individual to other available seating.\n\nIf the disabled individual cannot attend an event for which he/she has purchased tickets, please contact the Madison Square Garden Disabled Services Department at 212-465-6034 prior to the event taking place for further information. \n\nTickets for individuals with accessible needs, subject to availability, may be purchased in several ways:\n\n1) Online through Ticketmaster.com\n2) By phone to the Disabled Services Department at 888-609-7599\n3) By phone to Ticketmaster at 800-745-3000\n4) In-person by visiting the Madison Square Garden Box Office\n\nAssistive Listening Devices (ALD) are available at Guest Experience locations in the Arena. \n",
  'adaHours': 'For additional information regarding Access at Madison Square Garden or to discuss any other accommodations, please contact the Disabled Services Department at 888-609-7599 between the hours of 9:30am and 4:30pm, Monday - Friday. '},
 '_links': {'self': {'href': '/discovery/v2/venues/KovZpZA7AAEA?locale=en-us'}}}

In [129]:
# теперь посмотрим мероприятия на Madison Square Garden
VENUE_ID = "KovZpZA7AAEA"
url_events = "https://app.ticketmaster.com/discovery/v2/events.json"

params_events = {
    "apikey": TICKETMASTER_API_KEY,
    "venueId": VENUE_ID,
    "startDateTime": "2025-01-01T00:00:00Z",
    "endDateTime": "2025-02-01T00:00:00Z",
    "size": 20
}

In [130]:
response_events = requests.get(
    url_events,
    params=params_events,
    timeout=30
)

In [131]:
response_events.status_code

200

In [132]:
events_data = response_events.json()
type(events_data)

dict

In [133]:
events_data.keys()

dict_keys(['_links', 'page'])

In [134]:
events_data.get("page")

{'size': 20, 'totalElements': 0, 'totalPages': 0, 'number': 0}

In [135]:
params_events = {
    "apikey": TICKETMASTER_API_KEY,
    "venueId": VENUE_ID,
    "startDateTime": "2026-09-01T00:00:00Z",
    "endDateTime": "2027-01-01T00:00:00Z",
    "size": 20
}
response_events = requests.get(
    url_events,
    params=params_events,
    timeout=30
)

events_data = response_events.json()
events_data["page"]

{'size': 20, 'totalElements': 108, 'totalPages': 6, 'number': 0}

In [136]:
# Ticketmaster Discovery API не возвращает необходимые исторические события за 2025 год, 
# поэтому для этой задачи необходимо использовать другой источник

In [137]:
# MUSICBRAINZ

# Воспользуюсь сайтом MusicBrainz, для его использования API-ключ не нужен 

MUSICBRAINZ_EMAIL = os.getenv("MUSICBRAINZ_EMAIL")
MUSICBRAINZ_EMAIL is not None

True

In [138]:
headers = {
    "User-Agent": f"NYCTaxiEventsProject/0.1 ({MUSICBRAINZ_EMAIL})"
}

In [139]:
url_place = "https://musicbrainz.org/ws/2/place"

params_place = {
    "query": 'place:"Madison Square Garden" AND area:"New York"',
    "fmt": "json",
    "limit": 10
}
response_place = requests.get(
    url_place,
    params=params_place,
    headers=headers,
    timeout=30
)
response_place.status_code

200

In [140]:
place_data = response_place.json()
type(place_data)

dict

In [141]:
place_data.keys()

dict_keys(['created', 'count', 'offset', 'places'])

In [142]:
type(place_data["places"])

list

In [143]:
# для нашего запроса мы получили один ответ, выбор не требуется
len(place_data["places"])

1

In [145]:
place = place_data["places"][0]

print(f'name: {place["name"]}')
print(f'address: {place["address"]}')
print(f'id: {place["id"]}')

name: The Theater at Madison Square Garden
address: 4 Pennsylvania Plaza, New York, NY 10121
id: 679472ff-e860-46f6-a962-4c1181c9fd1e

In [146]:
# теперь посмотрим любые прошедшие мероприятия

url_event = "https://musicbrainz.org/ws/2/event"
PLACE_ID = place["id"]

params_event = {
    "query": f'pid:{PLACE_ID} AND begin:[2025-01-01 TO 2025-12-31]',
    "fmt": "json",
    "limit": 100
}
response_event = requests.get(
    url_event,
    params=params_event,
    headers=headers,
    timeout=30
)

In [147]:
response_event.status_code

200

In [148]:
event_data = response_event.json()
event_data.keys()

dict_keys(['created', 'count', 'offset', 'events'])

In [149]:
event_data["count"]

1

In [150]:
# Первый поиск по названию и району вернул The Theater at Madison Square Garden,
# а не основную арену. Поэтому необходимо найти и проверить основную площадку отдельно.

params_place = {
    "query": '"Madison Square Garden"',
    "fmt": "json",
    "limit": 100
}
response_place = requests.get(
    url_place,
    params=params_place,
    headers=headers,
    timeout=30
)

place_data = response_place.json()
type(place_data)

dict

In [151]:
len(place_data["places"])

3

In [152]:
for i, place in enumerate(place_data["places"]):
    print(i)
    print("name =", place.get("name"))
    print("id =", place.get("id"))
    print("type =", place.get("type"))
    print("address =", place.get("address"))
    print()

0
name = Madison Square Garden
id = a727b970-8ea0-4f75-abc8-db131f72aecb
type = Indoor arena
address = 4 Pennsylvania Plaza, New York, NY 10001

1
name = The Theater at Madison Square Garden
id = 679472ff-e860-46f6-a962-4c1181c9fd1e
type = Venue
address = 4 Pennsylvania Plaza, New York, NY 10121

2
name = Boston Garden
id = c8520d54-2c84-45cc-954a-52ac937da7ae
type = Indoor arena
address = 150 Causeway Street, Boston, MA 02114

In [153]:
# из-за слишком подробных параметров поиска изначально запрос вернул
# не основную площадку, а театр в ней под номером 1
# главная арена Madison Square Garden находится под номером 0, исходя из характеристик
# теперь посмотрим прошедшие мероприятия уже в ней

PLACE_ID = place_data["places"][0]["id"]

params_event = {
    "query": f'pid:{PLACE_ID} AND begin:[2025-01-01 TO 2025-12-31]',
    "fmt": "json",
    "limit": 100
}

response_event = requests.get(
    url_event,
    params=params_event,
    headers=headers,
    timeout=30
)

event_data = response_event.json()

In [154]:
# MusicBrainz хранит исторические события,
# но покрытие неполное: для Madison Square Garden за 2025 год
# найдено только 19 событий
# Поэтому MusicBrainz нельзя использовать как единственный источник полного списка концертов

event_data["count"]

19

In [155]:
# SETLIST.FM

# Setlist.fm должен содержать более полную историю концертов
# использую его для получения списка исторических мероприятий.

SETLISTFM_API_KEY = os.getenv("SETLISTFM_API_KEY")
SETLISTFM_API_KEY is not None

True

In [157]:
url_venue_setlist = "https://api.setlist.fm/rest/1.0/search/venues"
headers_setlist = {
    "Accept": "application/json",
    "x-api-key": SETLISTFM_API_KEY
}

params_venue_setlist = {
    "name": "Madison Square Garden",
    "cityName": "New York",
    "stateCode": "NY"
}
response_venue_setlist = requests.get(
    url_venue_setlist,
    params=params_venue_setlist,
    headers=headers_setlist,
    timeout=30
)
response_venue_setlist.status_code

200

In [158]:
venue_setlist_data = response_venue_setlist.json()
type(venue_setlist_data)

dict

In [159]:
venue_setlist_data.keys()

dict_keys(['type', 'itemsPerPage', 'page', 'total', 'venue'])

In [163]:
# основная арена под номером 1 с точным названием "Madison Square Garden"
for i, venue in enumerate(venue_setlist_data["venue"]):
    print(i)
    print("name =", venue.get("name"))
    print("id =", venue.get("id"))
    print("city =", venue.get("city"))
    print()

0
name = Hulu Theater at Madison Square Garden
id = 33d228a1
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

1
name = Madison Square Garden
id = 23d63cc7
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

2
name = The Theater at Madison Square Garden
id = 7bd62a20
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

3
name = Paramount Theatre
id = 7bd6c698
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

4
name = The Gunz Show Studio at Madison Square Garden
id = 1bd42dd4
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

5
name = The Paramount at Madison Square Garden
id = 23d2f42b
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

In [165]:
# посмотрим мероприятия, прошедшие в 2025 году и их количество
SETLIST_VENUE_ID = venue_setlist_data["venue"][1]["id"]
url_setlists = "https://api.setlist.fm/rest/1.0/search/setlists"

params_setlists = {
    "venueId": SETLIST_VENUE_ID,
    "year": "2025",
    "p": 1
}
response_setlists = requests.get(
    url_setlists,
    params=params_setlists,
    headers=headers_setlist,
    timeout=30
)
response_setlists.status_code

200

In [166]:
setlists_data = response_setlists.json()
setlists_data.keys()

dict_keys(['type', 'itemsPerPage', 'page', 'total', 'setlist'])

In [171]:
# Setlist.fm нашёл 179 записей для Madison Square Garden за 2025 год
# API возвращает по 20 записей на страницу, поэтому необходимо собрать все страницы

print('Всего записей за 2025 год:', setlists_data["total"])
print('Записей на одной странице:', len(setlists_data["setlist"]))

Всего записей за 2025 год: 179
Записей на одной странице: 20

In [176]:
import math
import time

total = setlists_data["total"]
items_per_page = setlists_data["itemsPerPage"]

total_pages = math.ceil(total / items_per_page)

# Первая страница у нас уже есть
all_setlists = setlists_data["setlist"].copy()

# Поэтому начинаем со второй страницы
for page in range(2, total_pages + 1):
    
    time.sleep(3.2)

    params_setlists = {
        "venueId": SETLIST_VENUE_ID,
        "year": "2025",
        "p": page
    }

    response = requests.get(
        url_setlists,
        params=params_setlists,
        headers=headers_setlist,
        timeout=30
    )

    if response.status_code != 200:
        print(f"Ошибка на странице {page}: {response.status_code}")
        break

    page_data = response.json()
    all_setlists.extend(page_data["setlist"])

In [179]:
# Собрали все 179 записей с 9 страниц
len(all_setlists)

179

In [181]:
# Проверим корректность и структуру полученных записей

print('Записей с уникальным id:', len({event["id"] for event in all_setlists}))

Записей с уникальным id: 179

In [185]:
print('Структура одной записи:', all_setlists[0].keys())
print('Пример одной записи:')
all_setlists[0]

Структура одной записи: dict_keys(['id', 'versionId', 'eventDate', 'lastUpdated', 'artist', 'venue', 'tour', 'sets', 'info', 'url'])
Пример одной записи:

{'id': '5b41bf10',
 'versionId': 'g736cea51',
 'eventDate': '31-12-2025',
 'lastUpdated': '2026-01-06T22:10:13.420+0000',
 'artist': {'mbid': 'e01646f2-2a04-450d-8bf2-0d993082e058',
  'name': 'Phish',
  'sortName': 'Phish',
  'disambiguation': 'American rock band formed in Burlington, Vermont, in 1983',
  'url': 'https://www.setlist.fm/setlists/phish-13d6ad51.html'},
 'venue': {'id': '23d63cc7',
  'name': 'Madison Square Garden',
  'city': {'id': '5128581',
   'name': 'New York',
   'state': 'New York',
   'stateCode': 'NY',
   'coords': {'lat': 40.7142691, 'long': -74.0059729},
   'country': {'code': 'US', 'name': 'United States'}},
  'url': 'https://www.setlist.fm/venue/madison-square-garden-new-york-ny-usa-23d63cc7.html'},
 'tour': {'name': "New Year's Run 2025"},
 'sets': {'set': [{'name': 'Set 1:',
    'song': [{'name': 'Free'},
     {'name': 'Birds of a Feather'},
     {'name': 'Bouncing Around the Room'},
     {'name': 'Stash'},
     {'name': 'Waste'},
     {'name': 'My Friend, My Friend'},
     {'name': 'A Life Beyond the Dream'},
     {'name': 'Kill Devil Falls'},
     {'name': 'More'},
     {'name': 'Monsters'},
     {'name': 'Life Saving Gun',
      'cover': {'mbid': '066a4f51-4230-4784-a2ca-daae7219e675',
       'name': 'Page McConnell & Trey Anastasio',
       'sortName': 'Page McConnell & Trey Anastasio',
       'disambiguation': '',
       'url': 'https://www.setlist.fm/setlists/page-mcconnell-and-trey-anastasio-1bf1d138.html'}}]},
   {'name': 'Set 2:',
    'song': [{'name': 'Sand', 'info': '>'},
     {'name': 'Fuego', 'info': '>'},
     {'name': "No Men in No Man's Land"},
     {'name': "What's Going Through Your Mind",
      'cover': {'mbid': '822b1e81-d1a0-47fb-b7f9-ef614b913603',
       'name': 'Trey Anastasio Band',
       'sortName': 'Trey Anastasio Band',
       'disambiguation': '',
       'url': 'https://www.setlist.fm/setlists/trey-anastasio-band-53d6d729.html'}},
     {'name': 'You Enjoy Myself', 'info': 'with "Fuego" teases from Trey'},
     {'name': "It's Ice",
      'info': 'halfway through the song an ice cream man came on stage ringing a cowbell) (>'},
     {'name': 'Cream',
      'cover': {'mbid': '070d193a-845c-479f-980e-bef15710653e',
       'name': 'Prince',
       'sortName': 'Prince',
       'disambiguation': '“The Artist Formerly Known as…”',
       'url': 'https://www.setlist.fm/setlists/prince-13d6b9ed.html'},
      'info': 'live debut by Phish) (with ice cream man walking around the venue ringing a cowbell'}]},
   {'name': 'Set 3:',
    'song': [{'name': 'Harry Hood',
      'info': 'with ice cream man, cows, dancers, and flying milk cartons; dancers left through ice cream freezer'},
     {'name': 'Also sprach Zarathustra, op. 30',
      'cover': {'mbid': '4cb43d82-824e-4034-b03d-1a98f36f6e16',
       'name': 'Richard Strauss',
       'sortName': 'Strauss, Richard',
       'disambiguation': 'German composer',
       'url': 'https://www.setlist.fm/setlists/richard-strauss-3d4ddcb.html'},
      'info': 'ice cream men brought out giant ice cream props; Trey moved to drums; Fish was given a helmet'},
     {'name': 'Auld Lang Syne',
      'cover': {'mbid': '56e7d9b7-174b-4e29-a50d-f164030d197f',
       'name': 'Robert Burns',
       'sortName': 'Burns, Robert',
       'disambiguation': '18th century Scottish poet/lyricist',
       'url': 'https://www.setlist.fm/setlists/robert-burns-4bd23756.html'},
      'info': 'a fake Fish rose from the freezer with a giant popsicle and blew up in the sky'},
     {'name': 'Tweezer',
      'info': 'with Meatstick teases; dancers from past NYE gags left the freezer and did the Meatstick dance) (>'},
     {'name': 'Piper',
      'info': 'with "Sneakin\' Sally Through the Alley" teases) (>'},
     {'name': 'Say It to Me S.A.N.T.O.S.'}]},
   {'encore': 1,
    'song': [{'name': 'Sincere',
      'cover': {'mbid': 'b042bb3d-912b-4e3f-a12b-e98675383b82',
       'name': 'Meredith Willson',
       'sortName': 'Willson, Meredith',
       'disambiguation': '',
       'url': 'https://www.setlist.fm/setlists/meredith-willson-53d49761.html'},
      'info': 'a cappella; live debut by Phish'},
     {'name': "Spock's Brain",
      'info': 'first time played since 7/14/2019) (>'},
     {'name': 'Tweezer Reprise'}]}]},
 'info': 'the band came out for the encore dressed as ice cream men',
 'url': 'https://www.setlist.fm/setlist/phish/2025/madison-square-garden-new-york-ny-5b41bf10.html'}

In [187]:
# Проверим наличие основных ключей в записях: id, eventDate, artist и venue есть во всех записях
# Поле tour присутствует только в 82 записях, что допустимо.
for key in ["id", "eventDate", "artist", "venue", 'tour']:
    print(
        key,
        sum(key in event for event in all_setlists)
    )

id 179
eventDate 179
artist 179
venue 179
tour 82

In [188]:
import pandas as pd

events = []

for event in all_setlists:
    events.append({
        "setlist_id": event["id"],
        "date": event["eventDate"],
        "artist": event["artist"]["name"],
        "venue": event["venue"]["name"],
        "tour": event.get("tour", {}).get("name"),
        "url": event["url"]
    })

df_events = pd.DataFrame(events)
df_events.head()

,setlist_id,date,artist,venue,tour,url
0,5b41bf10,31-12-2025,Phish,Madison Square Garden,New Year's Run 2025,https://www.setlist.fm/setlist/phish/2025/madi...
1,4b41bf16,30-12-2025,Phish,Madison Square Garden,New Year's Run 2025,https://www.setlist.fm/setlist/phish/2025/madi...
2,4b41bf0a,29-12-2025,Phish,Madison Square Garden,New Year's Run 2025,https://www.setlist.fm/setlist/phish/2025/madi...
3,5b41bf08,28-12-2025,Phish,Madison Square Garden,New Year's Run 2025,https://www.setlist.fm/setlist/phish/2025/madi...
4,6b4ea2f2,18-12-2025,Andrea Bocelli,Madison Square Garden,None,https://www.setlist.fm/setlist/andrea-bocelli/...

In [189]:
df_events.shape

(179, 6)

In [190]:
df_events.dtypes

setlist_id    object
date          object
artist        object
venue         object
tour          object
url           object
dtype: object

In [192]:
df_events["date"] = pd.to_datetime(df_events["date"], format="%d-%m-%Y")
df_events.dtypes

setlist_id            object
date          datetime64[ns]
artist                object
venue                 object
tour                  object
url                   object
dtype: object

In [197]:
# Setlist.fm хранит данные на уровне выступления артиста, а не мероприятия.
# Поэтому несколько setlist-записей в одну дату на одной площадке
# могут относиться к одному и тому же событию.
# Проверим записи, которые имеют одинаковую дату

print('Уникальных дат:', df_events["date"].nunique())

Уникальных дат: 89

In [201]:
events_per_date = (df_events.groupby("date").size().sort_values(ascending=False))

events_per_date.head(10)

date
2025-12-12    12
2025-08-15     5
2025-03-29     4
2025-07-23     3
2025-10-10     3
2025-07-14     3
2025-08-30     3
2025-10-31     3
2025-11-01     3
2025-05-30     3
dtype: int64

In [205]:
# Рассмотрим одну из дат с несколькими записями
df_events[df_events["date"] == "2025-12-12"]

,setlist_id,date,artist,venue,tour,url
6,7341cee1,2025-12-12,Ed Sheeran,Madison Square Garden,None,https://www.setlist.fm/setlist/ed-sheeran/2025...
7,5b41cb78,2025-12-12,Conan Gray,Madison Square Garden,None,https://www.setlist.fm/setlist/conan-gray/2025...
8,5b41cb70,2025-12-12,Nelly,Madison Square Garden,None,https://www.setlist.fm/setlist/nelly/2025/madi...
9,5341cb7d,2025-12-12,Laufey,Madison Square Garden,None,https://www.setlist.fm/setlist/laufey/2025/mad...
10,4b41cb7a,2025-12-12,Alex Warren,Madison Square Garden,None,https://www.setlist.fm/setlist/alex-warren/202...
11,4b41cb76,2025-12-12,Reneé Rapp,Madison Square Garden,None,https://www.setlist.fm/setlist/renee-rapp/2025...
12,4b41cb6a,2025-12-12,Zara Larsson,Madison Square Garden,None,https://www.setlist.fm/setlist/zara-larsson/20...
13,4341cb7f,2025-12-12,Jessie Murph,Madison Square Garden,None,https://www.setlist.fm/setlist/jessie-murph/20...
14,4341cb77,2025-12-12,Ravyn Lenae,Madison Square Garden,None,https://www.setlist.fm/setlist/ravyn-lenae/202...
15,4341cb73,2025-12-12,Myles Smith,Madison Square Garden,None,https://www.setlist.fm/setlist/myles-smith/202...
16,3341c8cd,2025-12-12,MONSTA X,Madison Square Garden,None,https://www.setlist.fm/setlist/monsta-x/2025/m...
17,1b4dbda8,2025-12-12,Kevin Woo,Madison Square Garden,None,https://www.setlist.fm/setlist/kevin-woo/2025/...

In [210]:
# 2025-12-12 явно происходило мероприятие с несколькими приглашёнными артистами
# 2025-07-23 проходил концерт из совместного тура The Tits Out Tour тур был Kesha и Scissor Sisters

# Для моего анализа не требуется восстанавливать структуру каждого концерта:
# достаточно знать, проходило ли музыкальное мероприятие на площадке в конкретную дату.
# Поэтому формирую календарь event days:
# одна уникальная комбинация "площадка + дата" означает день с концертом.

df_events[df_events["date"] == "2025-07-23"]

,setlist_id,date,artist,venue,tour,url
119,6346b253,2025-07-23,Kesha,Madison Square Garden,Tits Out,https://www.setlist.fm/setlist/kesha/2025/madi...
120,4b59df1a,2025-07-23,Scissor Sisters,Madison Square Garden,Tits Out,https://www.setlist.fm/setlist/scissor-sisters...
121,13464d05,2025-07-23,Vengaboys,Madison Square Garden,None,https://www.setlist.fm/setlist/vengaboys/2025/...

In [235]:
# Получаем искомую таблицу с датами, в которые проводили концерты в 2025 в Madison Square Garden

event_days = (
    df_events[["date", "venue"]]
    .drop_duplicates()
    .sort_values("date")
    .reset_index(drop=True)
)
event_days

         date                  venue
0  2025-01-08  Madison Square Garden
1  2025-03-07  Madison Square Garden
2  2025-03-08  Madison Square Garden
3  2025-03-10  Madison Square Garden
4  2025-03-21  Madison Square Garden
..        ...                    ...
84 2025-12-18  Madison Square Garden
85 2025-12-28  Madison Square Garden
86 2025-12-29  Madison Square Garden
87 2025-12-30  Madison Square Garden
88 2025-12-31  Madison Square Garden

[89 rows x 2 columns]

In [265]:
# ЧАСТЬ 2: Carnegie Hall

params_venue_setlist = {
    "name": "Carnegie Hall",
    "cityName": "New York",
    "stateCode": "NY"
}
response_venue_setlist = requests.get(
    url_venue_setlist,
    params=params_venue_setlist,
    headers=headers_setlist,
    timeout=30
)
response_venue_setlist.status_code

200

In [266]:
# выбираем площадку под номером 5, так как это основная сцена в Carnegie Hall
# она вмещает до 2804 человек, что сравнительно больше других сцен

venue_setlist_data = response_venue_setlist.json()
for i, venue in enumerate(venue_setlist_data["venue"]):
    print(i)
    print("name =", venue.get("name"))
    print("id =", venue.get("id"))
    print("city =", venue.get("city"))
    print()

0
name = Carnegie Hall
id = 7bd63668
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

1
name = Carnegie Chapter Hall
id = 43d5a31b
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

2
name = Carnegie Lyceum
id = 4bd0bb2e
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

3
name = Carnegie Recital Hall
id = 4bd58bd6
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

4
name = Chamber Music Hall
id = 3d539d7
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

5
name = Isaac Stern Auditorium
id = 43df974f
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

6
name = Recital Hall
id = 33d34495
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

7
name = Weill Recital Hall at Carnegie Hall
id = 1bd7596c
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

8
name = Zankel Hall at Carnegie Hall
id = 4bd58bd2
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

In [267]:
# Для остальных площадок использую тот же pipeline:
# получаю все setlist-записи за 2025 год и преобразую их
# в уникальные concert days по комбинации "дата + площадка".

CARNEGIE_VENUE_ID = venue_setlist_data["venue"][5]["id"]

params_setlists = {
    "venueId": CARNEGIE_VENUE_ID,
    "year": "2025",
    "p": 1
}
response_setlists = requests.get(
    url_setlists,
    params=params_setlists,
    headers=headers_setlist,
    timeout=30
)
setlists_data = response_setlists.json()
setlists_data.keys()
print('Всего записей за 2025 год для Isaac Stern Auditorium:', setlists_data["total"])

Всего записей за 2025 год для Isaac Stern Auditorium: 71

In [268]:
carnegie_setlists = setlists_data["setlist"].copy()
carnegie_total_pages = math.ceil(
    setlists_data["total"] / setlists_data["itemsPerPage"]
)

for page in range(2, carnegie_total_pages + 1):
    time.sleep(3.2)

    params_setlists = {
        "venueId": CARNEGIE_VENUE_ID,
        "year": "2025",
        "p": page
    }

    response = requests.get(
        url_setlists,
        params=params_setlists,
        headers=headers_setlist,
        timeout=30
    )

    if response.status_code != 200:
        print(f"Ошибка на странице {page}: {response.status_code}")
        break

    page_data = response.json()
    carnegie_setlists.extend(page_data["setlist"])
len(carnegie_setlists)

71

In [269]:
# аналогично 1 части, собираем уникальные концертные даты и получаем искомую таблицу
carnegie_events = []

for event in carnegie_setlists:
    carnegie_events.append({
        "setlist_id": event["id"],
        "date": event["eventDate"],
        "artist": event["artist"]["name"],
        "venue": event["venue"]["name"]
    })

carnegie_df_events = pd.DataFrame(carnegie_events)

carnegie_df_events["date"] = pd.to_datetime(
    carnegie_df_events["date"],
    format="%d-%m-%Y"
)
carnegie_event_days = (
    carnegie_df_events[["date", "venue"]]
    .drop_duplicates()
    .sort_values("date")
    .reset_index(drop=True)
)

carnegie_event_days

         date                   venue
0  2025-01-11  Isaac Stern Auditorium
1  2025-02-15  Isaac Stern Auditorium
2  2025-02-28  Isaac Stern Auditorium
3  2025-03-03  Isaac Stern Auditorium
4  2025-03-14  Isaac Stern Auditorium
5  2025-03-26  Isaac Stern Auditorium
6  2025-03-27  Isaac Stern Auditorium
7  2025-04-28  Isaac Stern Auditorium
8  2025-05-01  Isaac Stern Auditorium
9  2025-05-07  Isaac Stern Auditorium
10 2025-05-08  Isaac Stern Auditorium
11 2025-05-09  Isaac Stern Auditorium
12 2025-05-13  Isaac Stern Auditorium
13 2025-10-04  Isaac Stern Auditorium
14 2025-10-08  Isaac Stern Auditorium
15 2025-10-09  Isaac Stern Auditorium
16 2025-10-30  Isaac Stern Auditorium
17 2025-11-01  Isaac Stern Auditorium
18 2025-11-03  Isaac Stern Auditorium
19 2025-11-16  Isaac Stern Auditorium
20 2025-11-21  Isaac Stern Auditorium
21 2025-11-29  Isaac Stern Auditorium
22 2025-12-08  Isaac Stern Auditorium
23 2025-12-11  Isaac Stern Auditorium
24 2025-12-12  Isaac Stern Auditorium

In [270]:
# Для основной сцены Carnegie Hall найдена 71 запись,
# которая соответствует 25 уникальным концертным дням в 2025 году.
# Isaac Stern Auditorium at Carnegie Hall оставляю в анализе как контрастную по музыкальному профилю площадку.

In [271]:
# ЧАСТЬ 3: Radio City Music Hall
params_venue_setlist = {
    "name": "Radio City Music Hall",
    "cityName": "New York",
    "stateCode": "NY"
}
response_venue_setlist = requests.get(
    url_venue_setlist,
    params=params_venue_setlist,
    headers=headers_setlist,
    timeout=30
)
response_venue_setlist.status_code

200

In [272]:
venue_setlist_data = response_venue_setlist.json()
for i, venue in enumerate(venue_setlist_data["venue"]):
    print(i)
    print("name =", venue.get("name"))
    print("id =", venue.get("id"))
    print("city =", venue.get("city"))
    print()

0
name = Radio City Music Hall
id = 23d624c7
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

In [273]:
RADIO_CITY_VENUE_ID = venue_setlist_data["venue"][0]["id"]

params_setlists = {
    "venueId": RADIO_CITY_VENUE_ID,
    "year": "2025",
    "p": 1
}
response_setlists = requests.get(
    url_setlists,
    params=params_setlists,
    headers=headers_setlist,
    timeout=30
)
setlists_data = response_setlists.json()
setlists_data.keys()
print('Всего записей за 2025 год для Radio City Music Hall:', setlists_data["total"])

Всего записей за 2025 год для Radio City Music Hall: 108

In [274]:
radio_city_setlists = setlists_data["setlist"].copy()
radio_city_total_pages = math.ceil(
    setlists_data["total"] / setlists_data["itemsPerPage"]
)

for page in range(2, radio_city_total_pages + 1):
    time.sleep(3.2)

    params_setlists = {
        "venueId": RADIO_CITY_VENUE_ID,
        "year": "2025",
        "p": page
    }

    response = requests.get(
        url_setlists,
        params=params_setlists,
        headers=headers_setlist,
        timeout=30
    )

    if response.status_code != 200:
        print(f"Ошибка на странице {page}: {response.status_code}")
        break

    page_data = response.json()
    radio_city_setlists.extend(page_data["setlist"])
len(radio_city_setlists)

108

In [275]:
radio_city_events = []

for event in radio_city_setlists:
    radio_city_events.append({
        "setlist_id": event["id"],
        "date": event["eventDate"],
        "artist": event["artist"]["name"],
        "venue": event["venue"]["name"]
    })

radio_city_df_events = pd.DataFrame(radio_city_events)

radio_city_df_events["date"] = pd.to_datetime(
    radio_city_df_events["date"],
    format="%d-%m-%Y"
)
radio_city_event_days = (
    radio_city_df_events[["date", "venue"]]
    .drop_duplicates()
    .sort_values("date")
    .reset_index(drop=True)
)

radio_city_event_days

         date                  venue
0  2025-01-15  Radio City Music Hall
1  2025-01-24  Radio City Music Hall
2  2025-01-25  Radio City Music Hall
3  2025-02-14  Radio City Music Hall
4  2025-02-26  Radio City Music Hall
..        ...                    ...
57 2025-10-08  Radio City Music Hall
58 2025-10-10  Radio City Music Hall
59 2025-10-11  Radio City Music Hall
60 2025-12-14  Radio City Music Hall
61 2025-12-16  Radio City Music Hall

[62 rows x 2 columns]

In [ ]:
# Для Radio City Music Hall найдено 108 записей,
# соответствующих 62 уникальным концертным датам в 2025 году.

In [276]:
# ЧАСТЬ 4: Webster Hall
params_venue_setlist = {
    "name": "Webster Hall",
    "cityName": "New York",
    "stateCode": "NY"
}
response_venue_setlist = requests.get(
    url_venue_setlist,
    params=params_venue_setlist,
    headers=headers_setlist,
    timeout=30
)
response_venue_setlist.status_code

200

In [277]:
venue_setlist_data = response_venue_setlist.json()
for i, venue in enumerate(venue_setlist_data["venue"]):
    print(i)
    print("name =", venue.get("name"))
    print("id =", venue.get("id"))
    print("city =", venue.get("city"))
    print()

0
name = Balcony Room at Webster Hall
id = 63d572ef
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

1
name = Webster Hall
id = 6bd63a96
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

2
name = The Studio
id = 7bd60248
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

In [279]:
WEBSTER_VENUE_ID = venue_setlist_data["venue"][1]["id"]

params_setlists = {
    "venueId": WEBSTER_VENUE_ID,
    "year": "2025",
    "p": 1
}
response_setlists = requests.get(
    url_setlists,
    params=params_setlists,
    headers=headers_setlist,
    timeout=30
)
setlists_data = response_setlists.json()
setlists_data.keys()
print('Всего записей за 2025 год для Webster Hall:', setlists_data["total"])

Всего записей за 2025 год для Webster Hall: 195

In [281]:
webster_setlists = setlists_data["setlist"].copy()
webster_total_pages = math.ceil(
    setlists_data["total"] / setlists_data["itemsPerPage"]
)

for page in range(2, webster_total_pages + 1):
    time.sleep(3.2)

    params_setlists = {
        "venueId": WEBSTER_VENUE_ID,
        "year": "2025",
        "p": page
    }

    response = requests.get(
        url_setlists,
        params=params_setlists,
        headers=headers_setlist,
        timeout=30
    )

    if response.status_code != 200:
        print(f"Ошибка на странице {page}: {response.status_code}")
        break

    page_data = response.json()
    webster_setlists.extend(page_data["setlist"])
len(webster_setlists)

195

In [282]:
webster_events = []

for event in webster_setlists:
    webster_events.append({
        "setlist_id": event["id"],
        "date": event["eventDate"],
        "artist": event["artist"]["name"],
        "venue": event["venue"]["name"]
    })

webster_df_events = pd.DataFrame(webster_events)

webster_df_events["date"] = pd.to_datetime(
    webster_df_events["date"],
    format="%d-%m-%Y"
)
webster_event_days = (
    webster_df_events[["date", "venue"]]
    .drop_duplicates()
    .sort_values("date")
    .reset_index(drop=True)
)

webster_event_days

          date         venue
0   2025-01-17  Webster Hall
1   2025-01-23  Webster Hall
2   2025-02-01  Webster Hall
3   2025-02-07  Webster Hall
4   2025-02-08  Webster Hall
..         ...           ...
104 2025-12-09  Webster Hall
105 2025-12-12  Webster Hall
106 2025-12-13  Webster Hall
107 2025-12-14  Webster Hall
108 2025-12-18  Webster Hall

[109 rows x 2 columns]

In [283]:
# Отлично, из 195 записей получено 109 концертных дат в 2025 для Webster Hall

In [284]:
# ЧАСТЬ 5: Beacon Theatre
params_venue_setlist = {
    "name": "Beacon Theatre",
    "cityName": "New York",
    "stateCode": "NY"
}
response_venue_setlist = requests.get(
    url_venue_setlist,
    params=params_venue_setlist,
    headers=headers_setlist,
    timeout=30
)
response_venue_setlist.status_code

200

In [285]:
venue_setlist_data = response_venue_setlist.json()
for i, venue in enumerate(venue_setlist_data["venue"]):
    print(i)
    print("name =", venue.get("name"))
    print("id =", venue.get("id"))
    print("city =", venue.get("city"))
    print()

0
name = Beacon Theatre
id = bd6c9ba
city = {'id': '5128581', 'name': 'New York', 'state': 'New York', 'stateCode': 'NY', 'coords': {'lat': 40.7142691, 'long': -74.0059729}, 'country': {'code': 'US', 'name': 'United States'}}

In [286]:
BEACON_VENUE_ID = venue_setlist_data["venue"][0]["id"]

params_setlists = {
    "venueId": BEACON_VENUE_ID,
    "year": "2025",
    "p": 1
}
response_setlists = requests.get(
    url_setlists,
    params=params_setlists,
    headers=headers_setlist,
    timeout=30
)
setlists_data = response_setlists.json()
setlists_data.keys()
print('Всего записей за 2025 год для Beacon Theatre:', setlists_data["total"])

Всего записей за 2025 год для Beacon Theatre: 130

In [287]:
beacon_setlists = setlists_data["setlist"].copy()
beacon_total_pages = math.ceil(
    setlists_data["total"] / setlists_data["itemsPerPage"]
)

for page in range(2, beacon_total_pages + 1):
    time.sleep(3.2)

    params_setlists = {
        "venueId": BEACON_VENUE_ID,
        "year": "2025",
        "p": page
    }

    response = requests.get(
        url_setlists,
        params=params_setlists,
        headers=headers_setlist,
        timeout=30
    )

    if response.status_code != 200:
        print(f"Ошибка на странице {page}: {response.status_code}")
        break

    page_data = response.json()
    beacon_setlists.extend(page_data["setlist"])
len(beacon_setlists)

130

In [288]:
beacon_events = []

for event in beacon_setlists:
    beacon_events.append({
        "setlist_id": event["id"],
        "date": event["eventDate"],
        "artist": event["artist"]["name"],
        "venue": event["venue"]["name"]
    })

beacon_df_events = pd.DataFrame(beacon_events)

beacon_df_events["date"] = pd.to_datetime(
    beacon_df_events["date"],
    format="%d-%m-%Y"
)
beacon_event_days = (
    beacon_df_events[["date", "venue"]]
    .drop_duplicates()
    .sort_values("date")
    .reset_index(drop=True)
)

beacon_event_days

         date           venue
0  2025-01-17  Beacon Theatre
1  2025-01-18  Beacon Theatre
2  2025-01-28  Beacon Theatre
3  2025-02-21  Beacon Theatre
4  2025-02-22  Beacon Theatre
..        ...             ...
76 2025-12-13  Beacon Theatre
77 2025-12-15  Beacon Theatre
78 2025-12-16  Beacon Theatre
79 2025-12-30  Beacon Theatre
80 2025-12-31  Beacon Theatre

[81 rows x 2 columns]

In [ ]:
# Из 130 setlist-записей получена 81 уникальная концертная дата для Beacon Theatre в 2025 году.

In [289]:
# ЧАСТЬ 6: ТАБЛИЦА ДЛЯ 5 ПЛОЩАДОК 
all_event_days = pd.concat(
    [
        event_days,
        carnegie_event_days,
        radio_city_event_days,
        webster_event_days,
        beacon_event_days
    ],
    ignore_index=True
)

all_event_days = (
    all_event_days
    .sort_values(["date", "venue"])
    .reset_index(drop=True)
)

all_event_days

          date                   venue
0   2025-01-08   Madison Square Garden
1   2025-01-11  Isaac Stern Auditorium
2   2025-01-15   Radio City Music Hall
3   2025-01-17          Beacon Theatre
4   2025-01-17            Webster Hall
..         ...                     ...
361 2025-12-29   Madison Square Garden
362 2025-12-30          Beacon Theatre
363 2025-12-30   Madison Square Garden
364 2025-12-31          Beacon Theatre
365 2025-12-31   Madison Square Garden

[366 rows x 2 columns]

In [291]:
# Для удобства вывела количество концертных дней, для каждой из площадок, всего - 366 записей
all_event_days.groupby("venue").size().sort_values()

venue
Isaac Stern Auditorium     25
Radio City Music Hall      62
Beacon Theatre             81
Madison Square Garden      89
Webster Hall              109
dtype: int64

In [293]:
# ЧАСТЬ 7: TAXI ZONES КОНЦЕРТНЫХ ПЛОЩАДОК
# Координаты площадок получены вручную из Google Maps.
# Для каждой площадки координаты используются для определения Taxi Zone.
venues = pd.DataFrame({
    "venue": [
        "Madison Square Garden",
        "Isaac Stern Auditorium",
        "Radio City Music Hall",
        "Beacon Theatre",
        "Webster Hall"
    ],
    "latitude": [
        40.750591520873265,
        40.76514620273492,
        40.75999993740611,
        40.78050757471799,
        40.731705852947016
    ],
    "longitude": [
        -73.9934420610122,
        -73.97992017577518,
        -73.9799781831889,
        -73.9811761297521,
        -73.98922140568371
    ]
})

venues

                    venue   latitude  longitude
0   Madison Square Garden  40.750592 -73.993442
1  Isaac Stern Auditorium  40.765146 -73.979920
2   Radio City Music Hall  40.760000 -73.979978
3          Beacon Theatre  40.780508 -73.981176
4            Webster Hall  40.731706 -73.989221

In [294]:
# Проверка на правильность заполнения названий площадок
set(venues["venue"]) == set(all_event_days["venue"].unique())

True

In [295]:
import geopandas as gpd

taxi_zones = gpd.read_file(
    "../data/raw/taxi_zones/taxi_zones.shp"
)
taxi_zones.crs

<Projected CRS: EPSG:2263>
Name: NAD83 / New York Long Island (ftUS)
Axis Info [cartesian]:
- X[east]: Easting (US survey foot)
- Y[north]: Northing (US survey foot)
Area of Use:
- name: United States (USA) - New York - counties of Bronx; Kings; Nassau; New York; Queens; Richmond; Suffolk.
- bounds: (-74.26, 40.47, -71.8, 41.3)
Coordinate Operation:
- name: SPCS83 New York Long Island zone (US survey foot)
- method: Lambert Conic Conformal (2SP)
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [297]:
venues_gdf = gpd.GeoDataFrame(
    venues,
    geometry=gpd.points_from_xy(
        venues["longitude"],
        venues["latitude"]
    ),
    crs="EPSG:4326"
)
venues_gdf

                    venue   latitude  longitude                    geometry
0   Madison Square Garden  40.750592 -73.993442  POINT (-73.99344 40.75059)
1  Isaac Stern Auditorium  40.765146 -73.979920  POINT (-73.97992 40.76515)
2   Radio City Music Hall  40.760000 -73.979978     POINT (-73.97998 40.76)
3          Beacon Theatre  40.780508 -73.981176  POINT (-73.98118 40.78051)
4            Webster Hall  40.731706 -73.989221  POINT (-73.98922 40.73171)

In [298]:
venues_gdf = venues_gdf.to_crs(taxi_zones.crs)
venues_gdf.crs == taxi_zones.crs

True

In [304]:
# При выборе площадок я учитывала их географическое расположение
# Все выбранные площадки находятся в разных Taxi Zones Манхэттена,
# что позволяет анализировать локальный спрос в нескольких частях города.
# Isaac Stern Auditorium и Radio City Music Hall находятся относительно близко,
# но относятся к разным Taxi Zone.
# Isaac Stern Auditorium оставляю для разнообразия музыкального профиля:
# площадка ориентирована в том числе на классическую музыку.

venues_with_zones = gpd.sjoin(
    venues_gdf,
    taxi_zones[
        ["LocationID", "zone", "borough", "geometry"]
    ],
    how="left",
    predicate="within"
)
venues_with_zones

,venue,latitude,longitude,geometry,index_right,LocationID,zone,borough
0,Madison Square Garden,40.750592,-73.993442,POINT (986067.011 212737.465),185,186,Penn Station/Madison Sq West,Manhattan
1,Isaac Stern Auditorium,40.765146,-73.979920,POINT (989812.31 218040.78),162,163,Midtown North,Manhattan
2,Radio City Music Hall,40.760000,-73.979978,POINT (989796.669 216165.822),160,161,Midtown Center,Manhattan
3,Beacon Theatre,40.780508,-73.981176,POINT (989463.195 223637.364),238,239,Upper West Side South,Manhattan
4,Webster Hall,40.731706,-73.989221,POINT (987237.276 205856.932),78,79,East Village,Manhattan

In [305]:
all_event_days = all_event_days.merge(
    venues_with_zones[
        ["venue", "LocationID", "zone"]
    ],
    on="venue",
    how="left"
)

all_event_days

,date,venue,LocationID,zone
0,2025-01-08,Madison Square Garden,186,Penn Station/Madison Sq West
1,2025-01-11,Isaac Stern Auditorium,163,Midtown North
2,2025-01-15,Radio City Music Hall,161,Midtown Center
3,2025-01-17,Beacon Theatre,239,Upper West Side South
4,2025-01-17,Webster Hall,79,East Village
...,...,...,...,...
361,2025-12-29,Madison Square Garden,186,Penn Station/Madison Sq West
362,2025-12-30,Beacon Theatre,239,Upper West Side South
363,2025-12-30,Madison Square Garden,186,Penn Station/Madison Sq West
364,2025-12-31,Beacon Theatre,239,Upper West Side South
365,2025-12-31,Madison Square Garden,186,Penn Station/Madison Sq West

In [321]:
# ЧАСТЬ 8: СОХРАНЕНИЕ ОБРАБОТАННЫХ ДАННЫХ

from pathlib import Path

processed_events_dir = Path("../data/processed/events")
processed_events_dir.mkdir(parents=True, exist_ok=True)

# Таблица с данными когда и где были концерты
all_event_days.to_parquet(
    processed_events_dir / "event_days_2025.parquet",
    index=False
)

In [322]:
(processed_events_dir / "event_days_2025.parquet").exists()

True

In [323]:
venues_final = venues_with_zones[
    [
        "venue",
        "latitude",
        "longitude",
        "LocationID",
        "zone",
        "borough"
    ]
].reset_index(drop=True)

# Дополнительная таблица-справочник для 5 выбранных площадок
venues_final.to_parquet(
    processed_events_dir / "venues.parquet",
    index=False
)

In [324]:
(processed_events_dir / "venues.parquet").exists()

True